hl.workspace_rule({ workspace = "1", monitor = "eDP-1", default = true })
hl.workspace_rule({ workspace = "2", monitor = "eDP-1", default = true })
hl.workspace_rule({ workspace = "3", monitor = "eDP-1", default = true })
hl.workspace_rule({ workspace = "4", monitor = "eDP-1", default = true })
hl.workspace_rule({ workspace = "5", monitor = "eDP-1", default = true })
hl.workspace_rule({ workspace = "6", monitor = "eDP-1", default = true })
hl.workspace_rule({ workspace = "7", monitor = "eDP-1", default = true })
hl.workspace_rule({ workspace = "8", monitor = "eDP-1", default = true })
hl.workspace_rule({ workspace = "9", monitor = "eDP-1", default = true })
hl.workspace_rule({ workspace = "name:uwu", monitor = "eDP-1" })
