local profile = os.getenv("PROFILE")
local home = os.getenv("HOME")
hl.on("hyprland.start", function()
	hl.exec_cmd("hyprpm reload -n")
	hl.exec_cmd("waybar -c " .. home .. "/.local/share/groobarchy/waybar/config_" .. profile .. ".jsonc")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
end)
