input {
    kb_layout = gb
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1
    accel_profile = flat
  touchpad {
    disable_while_typing = true
  }
}

cursor {
    default_monitor = DP-2
    persistent_warps = true
    inactive_timeout = 10
}

device {
    name = logitech-g303-1
    accel_profile = flat
    sensitivity = -0.2

}

device {
    name = logitech-pro-x-2-1
    accel_profile = flat
    sensitivity = -0.2

}
