hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XCURSOR_SIZE", 24)
hl.env("HYPRCURSOR_SIZE", 24)
-- hl.env("QT_QPA_PLATFORM", "wayland;xcb")
-- hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
-- hl.env("QT_STYLE_OVERRIDE", "adwaita-dark")
--
-- hl.env("GDK_SCALE", 1)
-- hl.env("GDK_DPI_SCALE", 1)
-- hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 0)
-- hl.env("QT_SCALE_FACTOR", 1)
