$hypr = ~/.local/share/groob/dots/hypr

source = $hypr/shared/autostart.conf
source = $hypr/shared/general.conf
source = $hypr/shared/devices.conf
source = $hypr/shared/keybinds.conf
source = $hypr/shared/hy3.conf
source = $hypr/shared/rules.conf
source = $hypr/shared/animations.conf
source = $hypr/shared/decor.conf

source = $hypr/$PROFILE/monitors.conf
source = $hypr/$PROFILE/workspaces.conf
source = $hypr/$PROFILE/device-keybinds.conf
