[colors.primary]
background = "#0a0a0a"
foreground = "#c9c7cd"

[colors.cursor]
cursor = "#c1c0d4"

[colors.normal]
black   = "#27272a"
red     = "#b53c4a"
green   = "#90b99f"
yellow  = "#e6b99d"
blue    = "#aca1cf"
magenta = "#e29eca"
cyan    = "#ea83a5"
white   = "#757581"

[colors.bright]
black   = "#353539"
red     = "#d44657"
green   = "#9dc6ac"
yellow  = "#f0c5a9"
blue    = "#b9aeda"
magenta = "#ecaad6"
cyan    = "#f591b2"
white   = "#757581"

[font]
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[window]
dynamic_title = true
decorations   = "None"
opacity       = 0.8
