bind = CONTROL, 1, workspace, 1 # Switch to Workspace 1
bind = CONTROL, 2, workspace, 2 # Switch to Workspace 2
bind = CONTROL, 3, workspace, 3 # Switch to Workspace 3
bind = CONTROL, 4, workspace, 4 # Switch to Workspace 4
bind = CONTROL, 5, workspace, 5 # Switch to Workspace 5
bind = ALT, 1, workspace, 6 # Switch to Workspace 6
bind = ALT, 2, workspace, 7 # Switch to Workspace 7
bind = ALT, 3, workspace, 8 # Switch to Workspace 8
bind = ALT, 4, workspace, 9 # Switch to Workspace 9
bind = ALT, 5, workspace, 10 # Switch to Workspace 10
bind = SUPER, K, workspace, name:uwu # Switch to Workspace uwu?

bind = CONTROL SHIFT, 1, movetoworkspace, 1 # Move to Workspace 1
bind = CONTROL SHIFT, 2, movetoworkspace, 2 # Move to Workspace 2
bind = CONTROL SHIFT, 3, movetoworkspace, 3 # Move to Workspace 3
bind = CONTROL SHIFT, 4, movetoworkspace, 4 # Move to Workspace 4
bind = CONTROL SHIFT, 5, movetoworkspace, 5 # Move to Workspace 5
bind = ALT SHIFT, 1, movetoworkspace, 6 # Move to Workspace 6
bind = ALT SHIFT, 2, movetoworkspace, 7 # Move to Workspace 7
bind = ALT SHIFT, 3, movetoworkspace, 8 # Move to Workspace 8
bind = ALT SHIFT, 4, movetoworkspace, 9 # Move to Workspace 9
bind = ALT SHIFT, 5, movetoworkspace, 10 # Move to Workspace 10
bind = CONTROL SUPER, K, movetoworkspace, name:uwu # Move to Workspace uwu
